CREATE TABLE content (
    id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    content_type ENUM('movie', 'tv', 'anime') NOT NULL,
    tmdb_id INT UNSIGNED NULL,
    jikan_id INT UNSIGNED NULL,
    imdb_id VARCHAR(20) NULL,
    title VARCHAR(500) NOT NULL,
    original_title VARCHAR(500) NULL,
    overview TEXT NULL,
    poster_url VARCHAR(1000) NULL,
    backdrop_url VARCHAR(1000) NULL,
    release_date DATE NULL,
    end_date DATE NULL,
    runtime_minutes INT UNSIGNED NULL,
    status VARCHAR(50) NULL,
    rating_tmdb DECIMAL(3,1) NULL,
    rating_imdb DECIMAL(3,1) NULL,
    rating_rt VARCHAR(10) NULL,
    rating_metacritic INT UNSIGNED NULL,
    genres JSON NULL,
    total_seasons INT UNSIGNED NULL,
    total_episodes INT UNSIGNED NULL,
    metadata_updated_at TIMESTAMP NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_tmdb (tmdb_id, content_type),
    UNIQUE KEY uq_jikan (jikan_id),
    INDEX idx_content_type (content_type),
    INDEX idx_imdb (imdb_id)
) ENGINE=InnoDB;